=== Bharadwaj-Subcom/doki-theme-jetbrains/src/main/resources/theme-schema/jetbrains.theme.schema.json
{
  "version": "1.0",
  "definitions": {
  },
  "type": "object",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "required": [
    "id",
    "editorScheme",
    "overrides",
    "ui"
  ],
  "properties": {
    "id": {
      "type": "string",
      "title": "Theme Id",
      "description": "Unique Identifier for the theme.",
      "default": "",
      "pattern": "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$",
      "examples": [
        "91415015-8fe3-48eb-9951-70a5cd6cbb7f",
        "a14733d6-8e15-4e75-b6b8-509f323e5b3b"
      ]
    },
    "editorScheme": {
      "type": "object",
      "title": "The code colors",
      "required": [
        "type"
      ],
      "properties": {
        "type": {
          "type": "string",
          "description": "How you want to create the theme xml file.",
          "pattern": "(templateExtension)|(template)|(custom)",
          "default": "template",
          "examples": [
            "template",
            "templateExtension"
          ]
        },
        "file": {
          "type": "string",
          "description": "The name of the file you want to extend, take as template, or use directly.",
          "pattern": "^.+\\.xml$",
          "examples": [
            "Doki Light",
            "Doki Dark",
            "Natsuki_Light.xml",
            "Yuri_Dark.xml"
          ],
          "default": "Doki Light.xml"
        }
      }
    },
    "overrides": {
      "type": "object"
    },
    "ui": {
      "type": "object"
    }
  }
}

=== Bharadwaj-Subcom/doki-theme-jetbrains/buildSrc/assets/themes/eva/rei/dark/rei.dark.jetbrains.definition.json
{
  "id": "c262185d-9682-413b-9143-85a2dda76b2f",
  "editorScheme": {
    "type": "templateExtension",
    "file": "Rei_Dark.xml"
  },
  "overrides": {},
  "ui": {
    "ScrollBar.Transparent.thumbColor": "accentColorOverrideMoreTransparent",
    "ScrollBar.Transparent.thumbBorderColor": "accentColorOverrideMoreTransparent",
    "ScrollBar.Transparent.hoverThumbColor": "accentColorOverrideTransparent",
    "ScrollBar.Transparent.hoverThumbBorderColor": "accentColorOverrideTransparent",
    "ScrollBar.thumbBorderColor": "accentColorOverrideMoreTransparent",
    "ScrollBar.thumbColor": "accentColorOverrideMoreTransparent",
    "ScrollBar.hoverThumbBorderColor": "accentColorOverrideMoreTransparent",
    "ScrollBar.hoverThumbColor": "accentColorOverrideMoreTransparent",
    "ScrollBar.Mac.Transparent.thumbColor": "accentColorOverrideMoreTransparent",
    "ScrollBar.Mac.Transparent.thumbBorderColor": "accentColorOverrideMoreTransparent",
    "ScrollBar.Mac.Transparent.hoverThumbColor": "accentColorOverrideTransparent",
    "ScrollBar.Mac.Transparent.hoverThumbBorderColor": "accentColorOverrideTransparent",
    "ScrollBar.Mac.thumbBorderColor": "accentColorOverrideMoreTransparent",
    "ScrollBar.Mac.thumbColor": "accentColorOverrideMoreTransparent",
    "ScrollBar.Mac.hoverThumbBorderColor": "accentColorOverrideMoreTransparent",
    "ScrollBar.Mac.hoverThumbColor": "accentColorOverrideMoreTransparent"
  }
}

=== Bharadwaj-Subcom/doki-theme-jetbrains/buildSrc/assets/themes/reZero/echidna/dark/echidna.dark.jetbrains.definition.json
{
  "id": "b4d08c16-a891-4186-884d-e469cba72e99",
  "editorScheme": {
    "type": "template",
    "name": "Doki Dark"
  },
  "overrides": {
    "editorScheme": {
      "colors": {}
    }
  },
  "ui": {
    "Doki.Icon.Accent.Contrast.color": "headerColor",
    "ActionButton.pressedBackground": "selectionBackgroundTransparent",
    "ActionButton.pressedBorderColor": "#00000000"
  }
}

=== Bharadwaj-Subcom/doki-theme-jetbrains/buildSrc/assets/themes/reZero/emilia/dark/emilia.dark.jetbrains.definition.json
{
  "id": "696de7c1-3a8e-4445-83ee-3eb7e9dca47f",
  "editorScheme": {
    "type": "templateExtension",
    "file": "Emilia_Dark.xml"
  },
  "overrides": {},
  "ui": {
    "Plugins.lightSelectionBackground": "selectionBackground",
    "CompletionPopup.selectionBackground": "selectionBackground",
    "SearchEverywhere.Header.background": "headerColor",
    "SearchEverywhere.SearchField.background": "headerColor",
    "List.selectionBackground": "#5d3b70"
  }
}
